version: '3.8'

services:

  app:
    container_name: teste2024app
    image: mikep/teste2024app
    ports:
      - "16001:16001"
    depends_on:
      - api
    links:
      - api

  api:
    container_name: teste2024api
    image: mikep/teste2024api
    ports:
      - "16000:16000"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-init

  mongo-init:
    image: mongo:latest
    volumes:
      - ./dataset/dataset.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets/dataset.json --jsonArray